<?php
include('fns/minify/src/Minify.php');
include('fns/minify/src/ConverterInterface.php');
include('fns/minify/src/Converter.php');
include('fns/minify/src/NoConverter.php');
include('fns/minify/src/CSS.php');
include('fns/minify/src/JS.php');
include('fns/minify/src/Exception.php');
include('fns/minify/src/Exceptions/BasicException.php');
include('fns/minify/src/Exceptions/FileImportException.php');
include('fns/minify/src/Exceptions/IOException.php');