<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit10d8d817f119a2daaab28a7efbd43a1a
{
    public static $files = array (
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'VStelmakh\\UrlHighlight\\' => 23,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php72\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'VStelmakh\\UrlHighlight\\' => 
        array (
            0 => __DIR__ . '/..' . '/vstelmakh/url-highlight/src',
        ),
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit10d8d817f119a2daaab28a7efbd43a1a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit10d8d817f119a2daaab28a7efbd43a1a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit10d8d817f119a2daaab28a7efbd43a1a::$classMap;

        }, null, ClassLoader::class);
    }
}
